---
title: 'Cerner HealthFacts: Laboratory molecular biomarker results analysis'
output:
  html_document:
    df_print: paged
---

```{r include=F}
library(readr)
library(data.table)
library(plotly)
```

## Read data file for sample, representative year, due to size constraints.

```{r}
y <- 2016
fpath_in <- sprintf("cerner_hf_data/hf_labs-selected_results_OUT_%d.tsv.gz", y)
hf_results <- read_delim(fpath_in, delim = "\t", col_types = cols(.default = col_character(), admitted_dt_tm = col_datetime(), numeric_result = col_double(), normal_range_low = col_double(), normal_range_high = col_double()))
setDT(hf_results)
head(hf_results)
```

```{r}
message(sprintf("Columns: %s", paste(names(hf_results), collapse=", ")) )
```

```{r}
message(sprintf("Encounters: %s", hf_results[, uniqueN(encounter_id)]))
message(sprintf("accession: %s", hf_results[, uniqueN(accession)]))
message(sprintf("Lab_procedures: %s", hf_results[, uniqueN(lab_procedure_id)]))
message(sprintf("Result_units: %s", hf_results[, uniqueN(result_units_id)]))
```
```{r}
knitr::kable(unique(hf_results[, .(lab_procedure_id, lab_procedure_mnemonic, lab_procedure_name)][order(lab_procedure_name)]))
```

## Find and focus on results for PSA (prostate specific antigen)

```{r}
psa_ids <- unique(hf_results[grepl("PSA", lab_procedure_name, ignore.case=T), lab_procedure_id])
knitr::kable(unique(hf_results[lab_procedure_id %in% psa_ids, .(lab_procedure_id, lab_procedure_mnemonic, lab_procedure_name)]))
```
```{r}
hf_results[unit_display == "NULL", unit_display := NA]
hf_results[unit_desc == "NULL", unit_desc := NA]
knitr::kable(hf_results[lab_procedure_id == "1237" & !is.na(numeric_result) & !is.na(unit_display), .(lab_procedure_id, lab_procedure_mnemonic, numeric_result, unit_display, unit_desc)][sample(1:1e4, 50)])
```

## PSA units analysis

ng/mL predominant, so we keep only those.

```{r}
psa_units <- unique(hf_results[lab_procedure_id == "1237" & !is.na(numeric_result), .(unit_display, unit_desc)])
knitr::kable(psa_units)
table(hf_results[lab_procedure_id == "1237" & !is.na(numeric_result), unit_display])
```


## PSA value analysis
```{r}
hf_results_psa <- hf_results[lab_procedure_id == "1237" & !is.na(numeric_result) & unit_display == "ng/mL"]
sprintf("Lab procedure: %s, \"%s\"; values: %d; units: %s; min: %.1f; max: %.1f", hf_results_psa[, lab_procedure_mnemonic][1], hf_results_psa[, lab_procedure_name][1], hf_results_psa[, .N], unique(hf_results_psa[, unit_display]), min(hf_results_psa[, numeric_result]), max(hf_results_psa[, numeric_result]))
```

## Consider quantiles, and remove outlier values as likely spurious.

```{r}
q <- quantile(hf_results_psa[, numeric_result], probs = c(seq(0, .9, .1), seq(.91, .99, .01), seq(.991, 1, .001)))
psa_sane_max <- q["99%"]
hf_results_psa <- hf_results_psa[numeric_result <= psa_sane_max & numeric_result > 0]
data.table(percentiles = names(q), values = q)
```

```{r}
fig <- plot_ly(alpha = 0.8) %>% 
	add_histogram(x = hf_results_psa[, numeric_result], name = "PSA", marker = list(color = "deeppink"))
fig
```


