---
title: 'Cerner HealthFacts: Laboratory molecular biomarker results analysis'
output:
  html_document:
    df_print: paged
---

```{r include=F}
library(readr)
library(data.table)
library(plotly)
```

## Read data file for sample, representative year[s], due to size constraints.


```{r}
ifile <- "cerner_hf_data/hf_labs-selected_results_sex-agerange_OUT.tsv.gz"
hf_results <- read_delim(ifile, "\t", escape_double=F)
setDT(hf_results)
message(sprintf("Columns: %s", paste(names(hf_results), collapse=", ")) )
```

Remove rows missing essential values: gender, units

```{r}
hf_results <- hf_results[!is.na(gender)]
hf_results <- hf_results[!is.na(unit_display)]
hf_results <- hf_results[!is.na(numeric_result)]
hf_results <- hf_results[unit_display != "Not Mapped"]
message(sprintf("COUNTS: rows (lab results): %d; LOINC_CODEs: %d; GENEORPROTEIN_IDs: %d", nrow(hf_results), hf_results[, uniqueN(loinc_code)], hf_results[, uniqueN(geneOrProteinId)]))
message(sprintf("ADMITTED_YEARs: %s; \nGENDERs: %s; \nAGERANGEs: %s; \nUNITs: %s", 
                paste(unique(hf_results[["admitted_year"]]), collapse=", "),
                paste(unique(hf_results[["gender"]]), collapse=", "),
                paste(sort(unique(hf_results[["agerange"]])), collapse=", "),
                paste(sort(unique(hf_results[["unit_display"]])), collapse=", ")
                ))
```

For each GeneOrProtein ID, determine most common unit, generate summary statistics (mean, variance).

```{r}
gpids <- sort(unique(hf_results[["geneOrProteinId"]]))
report_dt <- data.table(gpid = gpids, labs = "", valcount = NaN, units = "", pref_units = "", pref_units_valcount = NaN, mean = NaN, sd = NaN)
for (i in 1:length(gpids)) {
  gpid <- report_dt$gpid[i]
  hf_results_this <- hf_results[geneOrProteinId == gpid]
  report_dt$labs[i] <- paste(unique(hf_results_this[["lab_procedure_mnemonic"]]), collapse=", ")
  report_dt$valcount[i] <- hf_results_this[, .N]
  tbl <- data.table(table(hf_results_this[["unit_display"]]))[order(-N)]
  units_preferred <- tbl[["V1"]][1]
  report_dt$units[i] <- paste(unique(hf_results_this[["unit_display"]]), collapse=", ")
  report_dt$pref_units[i] <- units_preferred
  report_dt$pref_units_valcount[i] <- tbl[["N"]][1]
  hf_results_this <- hf_results_this[unit_display == units_preferred]
  report_dt$mean[i] <- mean(hf_results_this[["numeric_result"]], na.rm=T)
  report_dt$sd[i] <- sd(hf_results_this[["numeric_result"]], na.rm=T)
}
write_delim(report_dt, "cerner_hf_data/results_analysis_report.tsv", "\t")
report_dt <- report_dt[order(-pref_units_valcount)]
knitr::kable(report_dt)
```

Plots

```{r}
plots <- list()
i_plot <- 0
for (i in 1:nrow(report_dt)) {
  i_plot <- i_plot + 1
  gpid <- report_dt$gpid[i]
  hf_results_this <- hf_results[geneOrProteinId == gpid]
  tbl <- data.table(table(hf_results_this[["unit_display"]]))[order(-N)]
  units_preferred <- tbl[["V1"]][1]
  hf_results_this <- hf_results_this[unit_display == units_preferred]
  plots[[i_plot]] <- plot_ly(type="histogram", x = hf_results_this[["numeric_result"]], name=sprintf("%d. %s", i_plot, gpid)) %>%
    layout(title = list(text=sprintf("%d. %s", i_plot, gpid), y=0.9, x=0.5, xanchor="center", yanchor="top"))
}
subplot(plots, nrows = 12) %>%
   layout(title="Molecular biomarker EHR lab value histograms")
```

